apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ccdh3zo45-python
  janus-idp.io/tekton: ccdh3zo45-python
  backstage.io/kubernetes-id: ccdh3zo45-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ccdh3zo45-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
