apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ccdh3zo45-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ccdh3zo45-python 
  name: ccdh3zo45-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ccdh3zo45-python 
